const ActionType = {
ADD_PATEINT:'ADD_PATEINT',
ADD_PATEINTSUCCESS:'ADD_PATEINTSUCCESS',
VIEW_PATEINT : 'VIEW_PATEINT',
VIEW_PATEINTSUCCESS : 'VIEW_PATEINTSUCCESS',
SEARCH_PATIENT : 'SEARCH_PATIENT',
SEARCH_PATIENTSUCCESS:'SEARCH_PATIENTSUCCESS',
SEARCH_BY_NAME :'SEARCH_BY_NAME',
SEARCH_BY_NAME_SUCCESS:'SEARCH_BY_NAME_SUCCESS',
SEARCH_BY_DATE:'SEARCH_BY_DATE',
SEARCH_BY_DATE_SUCCESS:'SEARCH_BY_DATE_SUCCESS',
DELETE_OBJECT:'DELETE_OBJECT',
DELETE_OBJECT_SUCCESS : 'DELETE_OBJECT_SUCCESS'

}


export default ActionType;